"""Add clients and client_locations tables

Revision ID: c159ce7c0683
Revises: 5f01627a2269
Create Date: 2026-01-29 13:21:06.341795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c159ce7c0683'
down_revision: Union[str, None] = '5f01627a2269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('data_imports', 'total_transactions',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('data_imports', 'imported_transactions',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('data_imports', 'duplicate_transactions',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index('ix_data_imports_created_at', table_name='data_imports')
    op.drop_index('ix_data_imports_location_id', table_name='data_imports')
    op.drop_index('ix_data_imports_square_account_id', table_name='data_imports')
    op.drop_index('ix_data_imports_status', table_name='data_imports')
    op.drop_constraint('data_imports_location_id_fkey', 'data_imports', type_='foreignkey')
    op.drop_constraint('data_imports_square_account_id_fkey', 'data_imports', type_='foreignkey')
    op.create_foreign_key(None, 'data_imports', 'locations', ['location_id'], ['id'])
    op.create_foreign_key(None, 'data_imports', 'square_accounts', ['square_account_id'], ['id'])
    op.alter_column('locations', 'address',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('locations', 'location_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('ix_locations_is_active', table_name='locations')
    op.drop_index('ix_locations_square_account_id', table_name='locations')
    op.drop_constraint('locations_square_location_id_key', 'locations', type_='unique')
    op.drop_index('ix_locations_square_location_id', table_name='locations')
    op.create_index(op.f('ix_locations_square_location_id'), 'locations', ['square_location_id'], unique=True)
    op.drop_constraint('locations_square_account_id_fkey', 'locations', type_='foreignkey')
    op.create_foreign_key(None, 'locations', 'square_accounts', ['square_account_id'], ['id'])
    op.drop_column('locations', 'updated_at')
    op.drop_column('locations', 'created_at')
    op.alter_column('square_accounts', 'access_token_encrypted',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('square_accounts', 'refresh_token_encrypted',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index('ix_square_accounts_organization_id', table_name='square_accounts')
    op.drop_constraint('square_accounts_square_merchant_id_key', 'square_accounts', type_='unique')
    op.drop_index('ix_square_accounts_square_merchant_id', table_name='square_accounts')
    op.create_index(op.f('ix_square_accounts_square_merchant_id'), 'square_accounts', ['square_merchant_id'], unique=True)
    op.drop_column('square_accounts', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('square_accounts', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_square_accounts_square_merchant_id'), table_name='square_accounts')
    op.create_index('ix_square_accounts_square_merchant_id', 'square_accounts', ['square_merchant_id'], unique=False)
    op.create_unique_constraint('square_accounts_square_merchant_id_key', 'square_accounts', ['square_merchant_id'])
    op.create_index('ix_square_accounts_organization_id', 'square_accounts', ['organization_id'], unique=False)
    op.alter_column('square_accounts', 'refresh_token_encrypted',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('square_accounts', 'access_token_encrypted',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('locations', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.add_column('locations', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.create_foreign_key('locations_square_account_id_fkey', 'locations', 'square_accounts', ['square_account_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_locations_square_location_id'), table_name='locations')
    op.create_index('ix_locations_square_location_id', 'locations', ['square_location_id'], unique=False)
    op.create_unique_constraint('locations_square_location_id_key', 'locations', ['square_location_id'])
    op.create_index('ix_locations_square_account_id', 'locations', ['square_account_id'], unique=False)
    op.create_index('ix_locations_is_active', 'locations', ['is_active'], unique=False)
    op.alter_column('locations', 'location_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('locations', 'address',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'data_imports', type_='foreignkey')
    op.drop_constraint(None, 'data_imports', type_='foreignkey')
    op.create_foreign_key('data_imports_square_account_id_fkey', 'data_imports', 'square_accounts', ['square_account_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('data_imports_location_id_fkey', 'data_imports', 'locations', ['location_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_data_imports_status', 'data_imports', ['status'], unique=False)
    op.create_index('ix_data_imports_square_account_id', 'data_imports', ['square_account_id'], unique=False)
    op.create_index('ix_data_imports_location_id', 'data_imports', ['location_id'], unique=False)
    op.create_index('ix_data_imports_created_at', 'data_imports', ['created_at'], unique=False)
    op.alter_column('data_imports', 'duplicate_transactions',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('data_imports', 'imported_transactions',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('data_imports', 'total_transactions',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_table('client_locations')
    op.drop_table('clients')
    # ### end Alembic commands ###
